### ISSUE TITLE
xrdfile: truncate's size arg has no default value

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdfs#20]
In PyFS.filelike, `f.truncate()` is equivalent to `f.truncate(f.tell())`.

Currently `xf.truncate()` raises an error b/c there's no default value for its size arg.

Proposed fix:
```
def truncate(self, size=None):
# after the mode check
if size is None:
  size = self.tell()
...
```

Should result in similar behaviour as in PyFS.

**Comment by lnielsen** [comment]
Great catch. LGTM

Can you also check that if you try to truncate a file open for reading that it throws an IOError (if it's not already tested):

```python
f = open(...,"r")
f.truncate()
---> IOError: File not open for writing
```
