### ISSUE TITLE
tests: directly compare result of operations on an xrdfile with a python file

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdfs#26]
Most of the tests assert that the result of some operation is equal to some constant (e.g. `assert xf.read() == ''`).
This is useful to ensure that it behaves as expected, it doesn't guarantee that the expected behaviour is correct.
While writing most of the tests for XRootDFile I've been manually verifying my assumptions about the behaviour of PyFS' filelike and Python file objects manually in a python prompt, updating the test to match and then fixing the code.

**Comment by lnielsen** [comment]
Can this issue be closed?

**Comment by otron** [comment]
Yup.
