### ISSUE TITLE
tests: XRootDFS/XRootDFile initialization parameters

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/xrootdfs#4]
Test parameters to the ``__init__`` methods of  ``XRootDFS`` and ``XRootDFile``.

**Comment by otron** [comment]
Do you mean the various parameters we don't currently do anything with?
(e.g. `thread_synchronize` and `timeout` for `XRootDFS`; `buffering`, `encoding`, `errors`, `newline`, `line_buffering` and `timeout` for `XRootDFile`)

I'm not sure how to go about writing tests for something that's not used for anything. Implementing the corresponding functionality for each parameter should be its own issue for each parameter.

**Comment by lnielsen** [comment]
Yes, testing of `XRootDFS`; `buffering`, `encoding`, `errors`, `newline`, `line_buffering` and `timeout` for `XRootDFile`. 

Most of them we likely don't support, but e.g. encoding/newline we should properly support.

**Comment by otron** [comment]
The idea being that the newline parameter is used to specify the value of newlines on the Filesystem?

**Comment by lnielsen** [comment]
pyxrootd uses only ``\n`` to detect newlines

**Comment by otron** [comment]
Excluding `encoding` and `errors` from this issue; see #51
