### ISSUE TITLE
tests: >98% test coverage

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/xrootdfs#5]
Ensure test coverage is above 98%. E.g. readlines/readline/xreadlines/__iter__/next methods are missing tests.

**Comment by otron** [comment]
Some of the untested code lines are when an error is raised when XRootD's status object's "ok" property is false (`if not statmsg.ok:`), which handle unspecified errors that I'm not sure how would occur or how to elicit through a test.
e.g. in `write()`.
Got any ideas, @lnielsen?

**Comment by lnielsen** [comment]
Now at 100% for all of the library so closing this one.
