### ISSUE TITLE
xrdfile: readline() ignores internal position pointer

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdfs#56]
Assume "test" is a file with contents = `1\n2\n3\n4\n`
```
xf = XRootDFile('test')
first_line = xf.readline()  # '1\n'
assert xf.tell() == 2  # Fails: 0 == 2
xf.seek(0)
assert first_line == xf.readline()  # Fails: '1\n' == '2\n'
```

* readline() doesn't update the ipp
* readline() reads from the start of the file or end of the previous line read until EOF or next newline character instead of starting at the IPP like python files do.

**Comment by lnielsen** [comment]
fixed in 4fa3e4a9334246fded264d45a205ee725d9d1ef7
