### ISSUE TITLE
xrdfile: _assert_mode defaults to `r+` if mode attribute is missing

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdfs#57]
This could potentially lead to strange situations as the underlying pyxrootd-file is given specific xrootd-flags depending on the mode it is opened in, and the mode defaults to `r`.
The only situation I can think of in which the mode attribute is missing is if it's been deleted. If this were to happen then we should instead raise an error rather than assume it was `r+` to avoid having to deal with a mismatch between `mode` and the xrootd flags set on the file.

**Comment by lnielsen** [comment]
Agree
