### ISSUE TITLE
tests: timeout parameter

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/xrootdfs#6]
Add a simple test of the timeout parameter

**Comment by otron** [comment]
Here's the pyxrootd documentation for the `timeout` parameter: http://xrootd.org/doc/python/xrootd-python-0.1.0/gettingstarted.html#timeouts

**Comment by otron** [comment]
Not sure what more to do here.
If we could simulate or enforce a delayed response from the server we could at least verify that it actually works for values <0.

**Comment by lnielsen** [comment]
You can use the mock library to fake a succesfull response from the server, but with an added side effect of waiting say 4 seconds and setting timeout to 2.

See example of mock in my latest PR #37 
https://github.com/inveniosoftware/xrootdfs/pull/37/files#diff-facf1bca6b1030a2239302befe6f5b2dR274

**Comment by lnielsen** [comment]
Here's an example (without Mock):

```python
import time
from functools import wraps

def test_timeout(tmppath):
    """Test timeout."""
    def delay(f, secs):
        @wraps(f)
        def inner(*args, **kwargs):
            time.sleep(secs)
            return f(*args, **kwargs)
        return inner

    fs = XRootDFS(mkurl(tmppath), timeout=1)
    fs.client.ping = delay(fs.client.ping, 2)
    fs.ping()
```

However, it seems like the timeout parameter doesn't really work. 

Looking at the XRootD source it suggests that it's in seconds (it's an integer and it gets added to a unix timestamp).

**Comment by lnielsen** [comment]
Timeout was removed from the library, and should be configured via environment variables so closing this issue.
