### ISSUE TITLE
Remove 'tmp=0' output

### ISSUE THREAD

**Issue by otron** [inveniosoftware/xrootdfs#64]
You know how, when we're running tests or whatever, just connecting to an xrootd-server via pyxrootd and `tmp=0` appears in the terminal?
It'd be nice if this didn't happen.
Dno why it happens, I've not been able to locate it in the XRootDFS source. So it's probably some pyxrootd artifact.

**Comment by lnielsen** [comment]
Don't know why - probably due to xrootd logging? Can you check if you can tweak via some of the environment variables (e.g XRD_LOGLEVEL). See http://xrootd.org/doc/man/xrdcp.1.html

**Comment by otron** [comment]
@lnielsen: Did Elvin not confirm it as a bug?

**Comment by otron** [comment]
Yup, when I spoke to Elvin on Friday he mentioned he'd gotten rid of the print in the latest version of xrootd. Since we know it's not caused by xrootdfs I'm closing this.
