### ISSUE TITLE
xrdfile: read() method should check status for errors.

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/xrootdfs#8]
```python
statmsg, res = self._file.read(
            offset=self._ipp,
            size=chunksize,
            timeout=self.timeout,
        )
```

**Comment by otron** [comment]
Noticed that `read()` doesn't check if the file is closed or not before attempting to read it.
Pyxrootd raises an error if you attempt to read a closed file.
We could either check if the file is open ourselves and raise the error if not (suggestion 1), or surround the call to `_file.read(...)` in a try-except block and pass the error upwards (suggestion 2).
I've opted for the first suggestion, as that seems more readable.

**Suggestion 1**:
```if self.closed:
    raise ValueError("I/O operation on closed file.")```

**Suggestion 2**:
```try:
    statmsg, res = self._file.read(
            offset=self._ipp,
            size=chunksize,
            timeout=self.timeout,
        )
except ValueError as err:
    raise err```

**Comment by lnielsen** [comment]
Does pyxrootd raise a ``ValueError``? If so I would just go with (2) (you can leave out the try/except block), otherwise I would go with (1). I guess we need to do the same for write and readlines methods

**Comment by otron** [comment]
Yup, pyxrootd raises a `ValueError` with the same error message as in (1) (which is the same one used by PyFS).

The problem with (2) is that it doesn't accurately mimic the behaviour of PyFS in the following scenario:
```
from fs.opener import opener
f = opener.open('file', 'w')
f.close()
f.read()
```

In this scenario PyFS raises a `ValueError`.
With (2), `_assert_mode()` gets called before `_file.read()`, resulting in an `IOError` being raised.

**Comment by lnielsen** [comment]
Got it. Makes sense what you have done in 7268dcf604082e2c5da9332d1da87b213bdbdd31
